spring:
  application:
    name: trade-service
  profiles:
    active: kafka, topics, trade-error
  kafka:
    listener:
      ack-mode: record

  config:
    import: configserver:http://34.50.50.170:13100

logging:
  level:
    org.springframework.kafka.listener.KafkaMessageListenerContainer: INFO