spring:
  application:
    name: trade-service
  profiles:
    active: kafka, topics, trade-error
  kafka:
    listener:
      ack-mode: record

  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOSTNAME:localhost}
    hostname: ${HOSTNAME:localhost}
    instance-id: "${HOSTNAME:${spring.application.name}}:${spring.application.name}:${server.port}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_SERVER_URL:http://34.64.58.121:8761/eureka/,http://34.64.104.174:8761/eureka/}"

logging:
  level:
    org.springframework.kafka.listener.KafkaMessageListenerContainer: INFO
