services:
  trade-service:
    container_name: trade-service
    image: ${AR_IMAGE_PATH}:${IMAGE_TAG}
    restart: always
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - /opt/trade-service/ssl:/app/ssl
      - /opt/trade-service/logs:/logs
    networks:
      - pgsg-network

  promtail:
    image: grafana/alloy:v1.16.1
    container_name: trade-service-promtail
    restart: always
    volumes:
      - /opt/trade-service/promtail-config.yml:/etc/promtail/config.yml
      - /opt/trade-service/logs:/logs
    command: run --config.format=promtail /etc/promtail/config.yml
    networks:
      - pgsg-network

networks:
  pgsg-network:
    external: true
